### ISSUE TITLE
Incorrect mapping of the neck

### ISSUE THREAD

**Issue by voanna** [Atif-Anwer/Mediapipe_to_OpenPose_JSON#1]
Hi I wanted to point out that at least the mapping of the neck is not correct.
If I take the list of OpenPose keypoints and re-order them according to the code here, the neck gets mapped to the nose.
https://github.com/Atif-Anwer/Mediapipe_to_OpenPose_JSON/blob/769821158d34eb58e8941f472142e9b8916bdfa2/src/mediapipe_JSON.py#L124

**Comment by Atif-Anwer** [comment]
Hi Thanks for looking into the script!

Since the neck point is not part of the estimated Mediapipe keypoints so I am calculating it by taking the middle of the shoulders as the assumed neck keypoint in the openpose format. Similarly for the Openpose MidHip point, the script calculates it from the ,oddle of the left and right hips detected by mediapipe. 

I was using the script to export the Openpose JSON for SMPL/SMPL-X models and it was generated correctly so I assumed that the neck was in the correct position. Can you possibly share the Openpose skeleton on the image so I can see if i can fix it?

**Comment by voanna** [comment]
I saw that you are estimating the neck keypoint by averaging the shoulder kpts, which is fine. 
I think that line should be 
```
mp_to_op_reorder = [0, 1, 12, 14, 16, 11, 13, 15, 0, 24, 26, 28, 23, 25, 27, 5, 2, 8, 7, 31, 31, 29, 32, 32, 30, 0, 0, 0, 0, 0, 0, 0, 0]
```
It is just changing the value of mp_to_op_reorder[1] from 0 to 1, since you set the tmp[1] to be [the neck keypoint here](https://github.com/Atif-Anwer/Mediapipe_to_OpenPose_JSON/blob/769821158d34eb58e8941f472142e9b8916bdfa2/src/mediapipe_JSON.py#L108)

**Comment by voanna** [comment]
I will add an image a bit later.
Also thank you for the quick response

**Comment by Atif-Anwer** [comment]
Thanks a bundle for pointing it out! It was a typo and the latest commit fixes it!
